name: CI

on:
  push:
    paths-ignore:
      - '.gitignore'
      - '**/.md'
      - 'assets/**'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '**/*.md'
      - 'assets/**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-12
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Procursus
      uses: beerpiss/procursus-action@v2
      with:
        packages: ldid xz-utils cmark make
        cache: true
        cache-path: ~/__cache
    - name: Set up Theos
      run: git clone --recursive --depth=1 'https://github.com/theos/theos.git' ~/theos
    - name: Install roothide headers
      run: |
        git clone --depth=1 'https://github.com/roothide/roothide.git' ~/roothide
        mkdir -p ~/theos/include ~/theos/lib
        cp ~/roothide/roothide.h ~/theos/include/
        cp ~/roothide/libroothide.tbd ~/theos/lib/

    - name: Build (rootful)
      run: |
        gmake clean package THEOS=~/theos
        mkdir -p /tmp/debs
        cp .theos/last_package /tmp/debs/rootful_path
        cp "$(cat .theos/last_package)" /tmp/debs/

    - name: Build (roothide)
      run: |
        gmake clean package THEOS=~/theos ROOTHIDE=1
        mkdir -p /tmp/debs
        cp .theos/last_package /tmp/debs/roothide_path
        cp "$(cat .theos/last_package)" /tmp/debs/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: NewTerm3
        path: /tmp/debs/*.deb